---
title: 'OMOP CDM v5.3'
format:
  html:
    toc: true
    toc-location: left
---

Below is the specification document for the OMOP Common Data Model, v5.3 (previously v5.3.1). Each table is represented with a high-level description and ETL conventions that should be followed. This is continued with a discussion of each field in each table, any conventions related to the field, and constraints that should be followed (like primary key, foreign key, etc). All tables should be instantiated in a CDM instance but do not need to be populated. Similarly, fields that are not required should exist in the CDM table but do not need to be populated. Should you have questions please feel free to visit the [forums](https://forums.ohdsi.org/) or the [github issue](https://github.com/ohdsi/CommonDataModel/issues) page.

*__Special Note__ This documentation previously referenced v5.3.1.  During the OHDSI/CommonDataModel Hack-A-Thon that occurred on August 18, 2021 the decision was made to align documentation with the minor releases.  Hot fixes and minor.minor release can be found through the searching of tags.*

```{r docLoop53, echo=FALSE, results='asis'}
source("R/specDocRenderer.R")
render_spec_doc(
  table_file = "../inst/csv/OMOP_CDMv5.3_Table_Level.csv",
  field_file = "../inst/csv/OMOP_CDMv5.3_Field_Level.csv"
)
```
