---
title: "Changes by Table"
format:
  html:
    toc: true
    toc-location: left
---
*from CDM v5.3 -> CDM v5.4*

For a full description of each table and field listed here, please see the [CDM v5.4 specification](cdm54.qmd).

Notation:

- a **\+** indicates an addition to the model, either a table or field
- a **->** indicates an alteration either in naming or specification
- a **-** indicates a subtraction from the model, either a table or field

## Summary

- **8** fields renamed
- **8** field definitions changed
- **22** fields added to existing tables, all non-required except for on (metadata_id)
- **3** tables added: `EPISODE`, `EPISODE_EVENT` and `COHORT`.
- **1** table removed: `ATTRIBUTE_DEFINITION`

## VISIT_OCCURRENCE
- `admitting_source_concept_id` -> `admitted_from_concept_id`
- `admitting_source_value` -> `admitted_from_source_value`
- `discharge_to_concept_id` -> `discharged_to_concept_id`
- `discharge_to_source_value` -> `discharged_to_source_value`

## VISIT_DETAIL
- `admitting_source_concept_id` -> `admitted_from_concept_id`
- `admitting_source_value` -> `admitted_from_source_value`
- `discharge_to_concept_id` -> `discharged_to_concept_id`
- `discharge_to_source_value` -> `discharged_to_source_value`
- `visit_detail_parent_id` -> `parent_visit_detail_id`

## PROCEDURE_OCCURRENCE
- \+ `procedure_end_date`
- \+ `procedure_end_datetime`

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| procedure_end_date | date | No | No | No |
| procedure_end_datetime | datetime | No | No | No |

## DEVICE_EXPOSURE
- `unique_device_id` -> Changed to `varchar(255)`
- \+ `production_id`
- \+ `unit_concept_id`
- \+ `unit_source_value`
- \+ `unit_source_concept_id`

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| production_id | varchar(255) | No | No | No |
| unit_concept_id | integer | No | No | Yes |
| unit_source_value | varchar(50) | No | No | No |
| unit_source_concept_id | integer | No | No | Yes |

## MEASUREMENT
- \+ `unit_source_concept_id`
- \+ `measurement_event_id`
- \+ `meas_event_field_concept_id`

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| unit_source_concept_id | integer | No | No | Yes |
| measurement_event_id | integer | No | No | No |
| meas_event_field_concept_id | integer | No | No | Yes |

## OBSERVATION
- \+ `value_source_value`
- \+ `observation_event_id`
- \+ `obs_event_field_concept_id`

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| value_source_value | varchar(50) | No | No | No |
| observation_event_id | integer | No | No | No |
| obs_event_field_concept_id | integer | No | No | Yes |

## NOTE
- \+ `note_event_id`
- \+ `note_event_field_concept_id`

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| note_event_id | integer | No | No | No |
| note_event_field_concept_id | integer | No | No | Yes |

## NOTE_NLP
- \+ `offset`

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| offset | varchar(50) | No | No | No |

## LOCATION
- \+ `country_concept_id`
- \+ `country_source_value`
- \+ `latitude`
- \+ `longitude`

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| country_concept_id | integer | No | No | Yes |
| country_source_value | varchar(80) | No | No | No |
| latitude | float | No | No | No |
| longitude | float | No | No | No |

## \+ EPISODE

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| episode_id | integer | Yes | Yes | No |
| person_id | integer | Yes | No | Yes |
| episode_concept_id | integer | Yes | No | Yes |
| episode_start_date | date | Yes | No | No |
| episode_start_datetime | datetime | No | No | No |
| episode_end_date | date | No | No | No |
| episode_end_datetime | datetime | No | No | No |
| episode_parent_id | integer | No | No | Yes |
| episode_number | integer | No | No | No |
| episode_object_concept_id | integer | Yes | No | Yes |
| episode_type_concept_id | integer | Yes | No | Yes |
| episode_source_value | varchar(50) | No | No | No |
| episode_source_concept_id | integer | No | No | Yes |

## \+ EPISODE_EVENT

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| episode_id | integer | Yes | No | Yes |
| event_id | integer | Yes | No | No |
| episode_event_field_concept_id | integer | Yes | No | Yes |

## METADATA
- \+ `metadata_id`
- \+ `value_as_number`

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| metadata_id | integer | Yes | Yes | No |
| value_as_number | float | No | No | No |

## CDM_SOURCE
- `cdm_source_name` -> Mandatory field
- `cdm_source_abbreviation` -> Mandatory field
- `cdm_holder` -> Mandatory field
- `source_release_date` -> Mandatory field
- `cdm_release_date` -> Mandatory field
- \+ `cdm_version_concept_id`

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| cdm_version_concept_id | integer | Yes | No | Yes |

## VOCABULARY
- `vocabulary_reference` -> Non-mandatory field
- `vocabulary_version` -> Non-mandatory field

## - ATTRIBUTE_DEFINITION

## \+ COHORT

| Field | Datatype | Required | Primary Key | Foreign Key |
|---|---|---|---|---|
| cohort_definition_id | integer | Yes | No | No |
| subject_id | integer | Yes | No | No |
| cohort_start_date | date | Yes | No | No |
| cohort_end_date | date | Yes | No | No |
