---
title: "OMOP CDM v6.0"
format:
  html:
    toc: true
    toc-location: left
---

## NOTE ABOUT CDM v6.0

Please be aware that v6.0 of the OMOP CDM is **not** fully supported by the OHDSI suite of tools and methods. The major difference in CDM v5.3 and CDM v6.0 involves switching the \*_datetime fields to mandatory rather than optional. This switch radically changes the assumptions related to exposure and outcome timing. Rather than move forward with v6.0, CDM v5.4 was designed with additions to the model that have been requested by the community while retaining the date structure of medical events in v5.3. Please see our the specifications for [CDM v5.4](https://ohdsi.github.io/CommonDataModel/cdm54.html) and detailed [changes from CDM v5.3](https://ohdsi.github.io/CommonDataModel/cdm54Changes.html). **For new collaborators to OHDSI, please transform your data to [CDM v5.4](https://github.com/OHDSI/CommonDataModel/releases/tag/v5.4.0) until such time that the v6 series of the CDM is ready for mainstream use.**

Below is the specification document for the OMOP Common Data Model, v6.0. Each table is represented with a high-level description and ETL conventions that should be followed. This is continued with a discussion of each field in each table, any conventions related to the field, and constraints that should be followed (like primary key, foreign key, etc). All tables should be instantiated in a CDM instance but do not need to be populated. Similarly, fields that are not required should exist in the CDM table but do not need to be populated. Should you have questions please feel free to visit the [forums](https://forums.ohdsi.org/) or the [github issue](https://github.com/ohdsi/CommonDataModel/issues) page.

## Changes in v6.0

- Latitude and Longitude added to [LOCATION](https://ohdsi.github.io/CommonDataModel/cdm60.html#location)
- Contract owner field added to [PAYER_PLAN_PERIOD](https://ohdsi.github.io/CommonDataModel/cdm60.html#payer_plan_period)
- All primary keys were changed to bigint
- The name of ADMISSION_SOURCE_CONCEPT_ID was changed to ADMITTED_FROM_CONCEPT_ID in [VISIT_OCCURRENCE](https://ohdsi.github.io/CommonDataModel/cdm60.html#visit_occurrence) and [VISIT_DETAIL](https://ohdsi.github.io/CommonDataModel/cdm60.html#visit_detail)
- All Concept_Ids are now mandatory except for UNIT_CONCEPT_ID, VALUE_AS_CONCEPT_ID, and OPERATOR_CONCEPT_ID. If there is no value available then a Concept_Id should be set to 0 instead of NULL.
- [DEATH](https://ohdsi.github.io/CommonDataModel/cdm531.html#death) table removed and DEATH_DATETIME field added to the [PERSON](https://ohdsi.github.io/CommonDataModel/cdm60.html#person) table. Cause of death is stored in the [CONDITION_OCCURRENCE](https://ohdsi.github.io/CommonDataModel/cdm60.html#condition_occurrence)
- DATETIME fields were made mandatory and date fields were made optional.

```{r docLoop60, echo=FALSE, results='asis'}
source("R/specDocRenderer.R")
render_spec_doc(
  table_file = "../inst/csv/OMOP_CDMv6.0_Table_Level.csv",
  field_file = "../inst/csv/OMOP_CDMv6.0_Field_Level.csv"
)
```
